[package]
name = "dns"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Xous DNS resolver"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.41"
log-server = { package = "xous-api-log", version = "0.1.37" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.37" }
xous-names = { package = "xous-api-names", version = "0.9.39" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
net = {path = "../net"}
xous-ipc = "0.9.41"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
trng = {path = "../trng"}

# for the time UX wart
# time UX is stuck here because the DNS crate has a lot of connections available
# and the more logically grouped status crate has run out of resources.
llio = {path = "../llio"}
pddb = {path = "../pddb"}
chrono = {version = "0.4.19", default-features = false, features = ["std"]}
sntpc = {version = "0.3.1"} #, features = ["log"]
locales = {path = "../../locales"}
gam = {path = "../gam"}
susres = {package = "xous-api-susres", version = "0.9.37"}
userprefs = {path = "../../libs/userprefs"}
modals = {path = "../modals"}

utralib = { version = "0.1.17", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
default = []
