[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Log output program"
edition = "2018"
name = "xous-log"
version = "0.1.28"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/xous-book/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-log = {package = "xous-api-log", version = "0.1.37"}
xous = "0.9.41"
xous-ipc = "0.9.41"
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}

utralib = {version = "0.1.17", optional = true, default-features = false }

# for USB serial logging
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"], optional = true}

[target.'cfg(target_arch = "arm")'.dependencies]
atsama5d27 = { git = "https://github.com/Foundation-Devices/atsama5d27.git", branch = "master", features = ["lcd-console"]}
xous = { version = "0.9.41", features = ["v2p"] } # v2p feature is used when lcd-console feature is turned on

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
atsama5d27 = ["utralib/atsama5d27"]

lcd-console = []
debugprint = [] # adding this allocates the UART for debugging the logger
logging = [] # adding this allocates the hardware UART for console interactions
usb = ["rkyv"]
#default = []
default = ["logging", "usb"]
# default = ["debugprint", "logging"]
