[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Provide high-resolution, non-rollover system time"
edition = "2018"
name = "xous-ticktimer"
version = "0.1.32"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/xous-book/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-ticktimer = "0.9.37"
xous = "0.9.41"
xous-ipc = "0.9.41"
xous-names = {package = "xous-api-names", version = "0.9.39"}
log-server = {package = "xous-api-log", version = "0.1.37"}
susres = {package = "xous-api-susres", version = "0.9.37"}
log = "0.4.14"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous-semver = "0.1.2"
utralib = {version = "0.1.17", optional = true, default-features = false }

[target.'cfg(target_arch = "arm")'.dependencies]
atsama5d27 = { git = "https://github.com/Foundation-Devices/atsama5d27.git", branch = "master" }

[features]
atsama5d27 = ["utralib/atsama5d27"]
precursor = ["utralib/precursor", "susres/precursor"]
hosted = ["utralib/hosted", "susres/hosted"]
renode = ["utralib/renode", "susres/renode"]
debug-print = []
watchdog = []
timestamp = []
# you may want to remove the watchdog feature if you're debugging a crash, as it will force the system to reboot automatically
default = ["watchdog"]
# default = []
# default = ["debug-print"]
