[package]
name = "modals"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Ux modals server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.41"
log-server = { package = "xous-api-log", version = "0.1.37" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.37" }
xous-names = { package = "xous-api-names", version = "0.9.39" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous-ipc = "0.9.41"
rkyv = {version = "0.4.3", features = ["const_generics"], default-features = false}
gam = {path="../gam"}
trng = {path="../trng"}
tts-frontend = {path="../tts"}
locales = {path = "../../locales"}
bit_field = "0.9.0"

utralib = { version = "0.1.17", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
tts = []
ditherpunk = []
hazardous-debug = []
default = []
