[package]
name = "spinor"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "SPINOR ROM operations server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.41"
log-server = { package = "xous-api-log", version = "0.1.37" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.37" }
xous-names = { package = "xous-api-names", version = "0.9.39" }
log = "0.4.14"
susres = {package = "xous-api-susres", version = "0.9.37"}
trng = { path = "../trng" }
com = { path = "../com" }
llio = { path = "../llio" }

rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
xous-ipc = "0.9.41"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}

utralib = { version = "0.1.17", optional = true, default-features = false }

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.7.3"

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
extra_flush = []
default = ["extra_flush"]

[lib]
test = true

[[bin]]
name = "spinor"
test = false