[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Graphical Abstraction Manager for Xous"
edition = "2018"
name = "gam"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
com = {path = "../com"} # used by the backlight setting on the main menu thread
content-plugin-api = {path = "../content-plugin-api"}
graphics-server = {path = "../graphics-server"}
ime-plugin-api = {path = "../ime-plugin-api"}
ime-plugin-shell = {path = "../ime-plugin-shell"}
keyboard = {path = "../keyboard"}
log = "0.4.14"
log-server = {package = "xous-api-log", version = "0.1.37"}
ticktimer-server = {package = "xous-api-ticktimer", version = "0.9.37"}
trng = {path = "../trng"}
xous = "0.9.41"
xous-ipc = "0.9.41"
xous-names = {package = "xous-api-names", version = "0.9.39"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

susres = {package = "xous-api-susres", version = "0.9.37"} # used for the sleep now menu item

enum_dispatch = "0.3.7" # used for trait-based dispatch off of multiple layout objects.
locales = {path = "../../locales"}

tts-frontend = {path="../tts"}

qrcode = { version = "0.12", default-features = false }
miniz_oxide = "0.4.4"
# pix = "0.13"

# used in bip39 dialogue
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
sha2 = {path="../engine-sha512"}
digest = "0.9.0"

utralib = {version = "0.1.17", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
debugprint = []
tts = []
# default = ["debugprint"] # "debugprint"
default = []
ditherpunk = []
