[package]
name = "trng"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "TRNG server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.41"
log-server = { package = "xous-api-log", version = "0.1.37" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.37" }
xous-names = { package = "xous-api-names", version = "0.9.39" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {package = "xous-api-susres", version = "0.9.37"}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
xous-ipc = "0.9.41"
rand_core = "0.5.1" # the 0.5.1 API is necessary for compatibility with curve25519-dalek crates
utralib = { version = "0.1.17", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
debugprint = []
default = [] # "debugprint"
