[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "COM interface to the EC"
edition = "2018"
name = "com"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
com_rs-ref = {path = "../../imports/com_rs-ref"}
log = "0.4.14"
log-server = {package = "xous-api-log", version = "0.1.37"}
ticktimer-server = {package = "xous-api-ticktimer", version = "0.9.37"}
susres = {package = "xous-api-susres", version = "0.9.37"}
typenum = "1.12"
xous = "0.9.41"
xous-ipc = "0.9.41"
xous-names = {package = "xous-api-names", version = "0.9.39"}
trng = {path = "../trng"}
llio = {path = "../llio"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

xous-semver = "0.1.2"

utralib = {version = "0.1.17", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
debugprint = []
default = [] # "debugprint"
fccagent = []
#default = ["debugprint"] # , "fccagent"
