[package]
name = "aes"
version = "0.8.1"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "AES library for Xous"

# Dependency versions enforced by Cargo.lock.
[dependencies]
cipher = "0.4.2"

[features]
hazmat = [] # Expose cryptographically hazardous APIs
default = []
